version: '3.8'
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "y"
      SA_PASSWORD: "C001b!u3pa55w0rd!"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"

      